  spring:
    application:
      name: identity-service
    datasource:
      url: ${DBMS_CONNECTION}
      driverClassName: "com.mysql.cj.jdbc.Driver"
      username: ${DBMS_USERNAME}
      password: ${DBMS_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    kafka:
      bootstrap-servers: YOU_URL
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  server:
    port: 7777
    servlet:
      context-path: /identity

  jwt:
    signerKey: "YOU_SIGNER_KEY"
    valid-duration: 6000 # in second
    refreshtable-duration: 1200 # in seconds

  outbound:
    identity:
      client-id: "YOU_CLIENT_ID"
      client-secret: "YOU_CLIENT_SECRET"
      redirect-uri: "YOU_REDIRECT_URI"

  app:
    services:
      profile: YOU_PROFILE_URL
      book: YOU_BOOK_URL
      payment: YOU_PAYMENT_URL

  vnpay:
    payment-url: "YOU_PAYMENT_URL"
    tmn-code: "YOU_TMN_CODE"
    hash-secret: "YOU_HASH_SECRET"

