server:
  port: 8083
  servlet:
    multipart:
      max-file-size: 500MB    # Kích thước tối đa của một file
      max-request-size: 500MB # Kích thước tối đa của toàn bộ request
    context-path: /post

spring:
  data:
    mongodb:
      port: 27018
      database: post


cloudinary:
  cloud_name: "YOU_CLOUD_NAME"
  api_key: "YOU_API_KEY"
  api_secret: "YOU_SECRET_KEY"
