server:
  port: 8084
  servlet:
    context-path: /book

spring:
  data:
    mongodb:
      port: 27017
      database: bookstore

cloudinary:
  cloud-name: "YOU_CLOUD_NAME"
  api-key: "API_KEY"
  api-secret: "API_SECRET"
