server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: YOUR_MONGODB_URI

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: YOUR_ISSUER_URI

idp:
  url: YOUR_URL
  client-id: YOUR_CLIENT_ID
  client-secret: YOUR_CLIENT_SECRET
