server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:7777
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: book-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/book/**
          filters:
            - StripPrefix=2
        - id: friend-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/friend/**
          filters:
            - StripPrefix=2
        - id: comment-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/comment/**
          filters:
            - StripPrefix=2
        - id: interaction-service
          uri: http://localhost:8089
          predicates:
            - Path=${app.api-prefix}/interaction/**
          filters:
            - StripPrefix=2
        - id: messaging-service
          uri: http://localhost:8090
          predicates:
            - Path=${app.api-prefix}/messaging/**
          filters:
            - StripPrefix=2